# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 01:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 9, 24, 1, 56, 41, 144724, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
