# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20171003_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=250),
        ),
    ]
